name: test workflow
on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v4

      - uses: action/setup-node@v4
        with:
          node-version: 20

      - name: Get code
        run: npm install

      - name: run tests
        run: npm test
